# Generated by Django 3.2.11 on 2022-04-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
